use macos-14 (#54)
build on macos-14

diff --git a/.github/workflows/MacOs.yml b/.github/workflows/MacOs.yml
--- a/.github/workflows/MacOs.yml
+++ b/.github/workflows/MacOs.yml
@@ -1,4 +1,4 @@
-name: MacOs-15-openmpi
+name: MacOs-14-openmpi
 # This workflow is designed to run on MacOs
 on:
   push:
@@ -35,22 +35,32 @@ on:
 jobs:
   build:
 
-    runs-on: macos-latest
+    runs-on: macos-14
 
     steps:
     - uses: actions/checkout@v4
     - name: Install dependencies
       run: |
-        brew install m4 git bison hdf5 wget autoconf automake gcc open-mpi gmsh scotch scalapack openblas
- #       export HOMEBREW_CC=gcc-15
- #       export HOMEBREW_CXX=g++-15
- #       brew reinstall open-mpi  --build-from-source
+        brew install gcc m4 git bison hdf5 wget autoconf automake open-mpi gmsh scotch scalapack openblas
+
+    - name: gfortran symlink for MPI
+      run: |
+        ln -sfn $(brew --prefix)/bin/gfortran-15 /opt/homebrew/bin/gfortran
+        which gfortran
+        gfortran --version
+
     - name: configure
       run: |
+        export SYSROOT=$(xcrun --sdk macosx --show-sdk-path)
         autoreconf -i && ./configure --prefix="${HOME}/psd" --with-dependencies=yes CC=gcc-15 CXX=g++-15 FC=gfortran-15 F77=gfortran-15
     - name: make
       run: |
-        make
+        set +e                      # Don't exit immediately on failure
+        export SYSROOT=$(xcrun --sdk macosx --show-sdk-path)
+        make SYSROOT=$SYSROOT
+        status=$?                  # Capture exit code of make
+        find . \( -name "*.log" -o -name "*.txt" \) -exec rsync -R {} "$GITHUB_WORKSPACE/artifacts/" \; || true
+        exit $status               # Re-raise make status to mark the step as failed if it should
     #     make install
 
     # - name: make check and save logs
@@ -62,6 +72,10 @@ jobs:
     #     find . \( -name "*.log" -o -name "*.txt" \) -exec cp --parents {} "$GITHUB_WORKSPACE/artifacts/" \; || true
     #     exit $status               # Re-raise make check's status to mark the step as failed if it should
 
+    - name: Collect build artifacts
+      run: |
+        mkdir -p "$GITHUB_WORKSPACE/artifacts"
+        find . -type f \( -name "*.log" -o -name "*.txt"  \) -exec cp --parents {} "$GITHUB_WORKSPACE/artifacts/" \; || true
 
     - name: Upload logs
       if: always()  # upload logs even if test failed
