upload artifacts even when check fail

diff --git a/.github/workflows/Ub24-mpich.yml b/.github/workflows/Ub24-mpich.yml
--- a/.github/workflows/Ub24-mpich.yml
+++ b/.github/workflows/Ub24-mpich.yml
@@ -44,12 +44,16 @@ jobs:
     - name: make
       run: |
         make && make install
-    - name: make check
+
+    - name: make check and save logs
       run: |
+        set +e                      # Don't exit immediately on failure
         make check
-        # Save the log file(s) as an artifact
-        mkdir -p $GITHUB_WORKSPACE/artifacts
+        status=$?                  # Capture exit code of make check
+        mkdir -p "$GITHUB_WORKSPACE/artifacts"
         find . \( -name "*.log" -o -name "*.txt" \) -exec cp --parents {} "$GITHUB_WORKSPACE/artifacts/" \; || true
+        exit $status               # Re-raise make check's status to mark the step as failed if it should
+
 
     - name: Upload logs
       if: always()  # upload logs even if test failed
